### ISSUE TITLE
Shuttle item selection overwrites existing selection

### ISSUE THREAD

**Issue by JFaryj** [dataconsulting-pl/APEX-Low-Test-Framework#14] opened 2022-11-12 12:41 UTC
Rule "user moves value(s) {listOfStrings} in {string} shuttle item" sets value(s) in shuttle item so existing selection is lost

**Test to reproduce:**

Background: User access Activities page
    Given the user access the 'https://apex.oracle.com/pls/apex/f?p=59118' url
    And user entered '{username}' in 'username' field
    And user entered '{password}' in 'password' field
    And user clicked on the 'Sign In' button
    And waiting for 1 seconds

Scenario: Set Shuttle Box - Single
  When user moves values 'Option 2' in 'Shuttle Item' shuttle item
  And waiting for 2 seconds
  Then value 'Option 2' in 'Shuttle Item' shuttle item is chosen
  And waiting for 2 seconds
  And user moves values 'Option 1' in 'Shuttle Item' shuttle item
  Then value 'Option 1' in 'Shuttle Item' shuttle item is chosen
  And waiting for 2 seconds
  And user moves values 'Option 2' in 'Shuttle Item' shuttle item
  And waiting for 2 seconds

**Expected result:** 
Both items are selected in shuttle item

**Comment by borowskikrz** [comment] 2022-11-17 10:07
Duplicate of issue 13.

**Closed as completed by borowskikrz** 2022-11-17 10:07 UTC
Labels: bug, duplicate
